/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CurrencyExchange;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setMinHeight(350);
        primaryStage.setMinWidth(350);
        primaryStage.initStyle(StageStyle.TRANSPARENT);
        primaryStage.setTitle("Currency XChange");


        Button btn = new Button();
        btn.setText("Go to page");
        btn.setOnAction((event) -> {
            System.out.println("Currency XChange");
            primaryStage.setScene(ConvertScene.getScene());
        });
        
        StackPane root = new StackPane();
        root.getChildren().add(btn);
        primaryStage.setScene(new Scene(root, 640, 480));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
